version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: nexus_opera_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: mini_erp_crm
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nexus_opera_app
    restart: always
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      DATABASE_URL: postgresql://postgres:1234@postgres:5432/mini_erp_crm
      JWT_SECRET: super_secret_jwt_key_mini_erp_crm_2026
      JWT_EXPIRES_IN: 24h
    depends_on:
      - postgres

volumes:
  postgres_data:
